### ISSUE TITLE
Any pure cmd tool project?

### ISSUE THREAD

**Issue by MatthewP-Newbee** [junjiezhujason/aegis#4]
Hello, will you develope pure command line tool? Or R/python package. Thanks.

**Comment by junjiezhujason** [comment]
The interactive visualization relies on the frontend HTML + JS to render
but python is really powering the backend. If your goal is to use some of
the statistical or layout submodules, you can use them directly with
python. So you can adapt the python code for your application.
This is the example on our webpage of a benchmark that calls our customized
graph object: http://aegis.stanford.edu/notebooks/aegis_benchmark_part1.html
.

Hope this helps,
Jason
